# Generated by Django 4.2.7 on 2024-03-02 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rom_url',
            field=models.URLField(default=datetime.datetime(2024, 3, 2, 8, 21, 9, 413632, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
