# Generated by Django 4.2.7 on 2024-03-02 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_game_rom_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rom_url',
        ),
        migrations.AddField(
            model_name='game',
            name='embed_code',
            field=models.TextField(default=datetime.datetime(2024, 3, 2, 8, 28, 23, 323170, tzinfo=datetime.timezone.utc), max_length=500),
            preserve_default=False,
        ),
    ]
