# Generated by Django 4.2.7 on 2024-03-02 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_game_rom_url_game_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rom_file',
            field=models.FileField(default=datetime.datetime(2024, 3, 2, 10, 13, 3, 252664, tzinfo=datetime.timezone.utc), upload_to='dendy/'),
            preserve_default=False,
        ),
    ]
