# Generated by Django 4.2.7 on 2024-03-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_game_rom_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='embed_code',
        ),
    ]
